export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const REGISTER_TWO_STEP_REQUEST = "REGISTER_TWO_STEP_REQUEST"
export const REGISTER_TWO_STEP_SUCCESS = "REGISTER_TWO_STEP_SUCCESS"
export const REGISTER_TWO_STEP_FAILURE = "REGISTER_TWO_STEP_FAILURE"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST"
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS"
export const SEND_RESET_PASSWORD_FAILURE = "SEND_RESET_PASSWORD_FAILURE"


export const VERIFY_RESET_PASSWORD_REQUEST = "VERIFY_RESET_PASSWORD_REQUEST"
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS"
export const VERIFY_RESET_PASSWORD_FAILURE = "VERIFY_RESET_PASSWORD_FAILURE"